export enum TransactionCategory {
  FOOD_DRINK = 'FOOD_DRINK',
  SHOPPING = 'SHOPPING',
  HOUSING = 'HOUSING',
  TRANSPORTATION = 'TRANSPORTATION',
  ENTERTAINMENT = 'ENTERTAINMENT',
  HEALTH = 'HEALTH',
  INVESTMENT = 'INVESTMENT',
  INCOME = 'INCOME',
  OTHERS = 'OTHERS',
}
